# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For  more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: auto-update

on:
  push:
    branches:
      - "master"
      - "releases/**"
  schedule:
    - cron:  '0 0 */3 * *'
permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: run python script
        run: |
          python main.py
      - name: rename csv
        run: |
          cp loongapplist-latest.csv loongapplist-$(date '+%Y-%m-%d').csv
      - name: Set date env
        run:  |
          echo "TODAY=$(date '+%Y/%m/%d')" >> $GITHUB_ENV
          echo "FILENAME=loongapplist-$(date '+%Y-%m-%d').csv" >> $GITHUB_ENV
      - name: Commit and push changes
        id: commit
        run: |
          git config --global user.name "Github Action"
          git config --global user.email "Action@github.com"
          git add loongapplist-latest.csv
          git commit -m "auto update" -a
          git push
      - name: Update Release Everyday
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ env.FILENAME }}
          tag_name: ${{ env.TODAY }}
          name: ${{ env.TODAY }}
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
      - name: Update latest Release
        uses: softprops/action-gh-release@v1
        with:
          files: loongapplist-latest.csv
          tag_name: latest
          name: Latest
        env:
          GITHUB_TOKEN: ${{ secrets.UPDATE_TOKEN }}
